### ISSUE TITLE
Can't add odd numbers of elements.

### ISSUE THREAD

**Issue by mschout** [mfcovington/Number-RangeTracker#4]
You cannot add odd numbers of elements to a range.  E.g.:

```$range->add( [ 0, 1, 2 ] )```

will fail with: "Odd number of elements in input ranges (start/stop pairs expected)"

**Comment by mfcovington** [comment]
Hi @mschout, `$range->add()` expects pairs of numbers in order to form the boundaries of ranges to track. So, in your case, you could use:

```perl
$range->add( [ 0, 2 ] )
```

If you want to add one number at a time, you can use:

```perl
$range->add( [ 0, 0 ] )
$range->add( [ 1, 1 ] )
$range->add( [ 2, 2 ] )
```

Or even this:

```perl
$range->add( [ 0, 0 ], [ 1, 1 ], [ 2, 2 ] )
```

**Comment by mschout** [comment]
I think Set::IntSpan does what I need anyway -- given a list of numbers, compute the ranges.  Thanks
